// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title IPoseidonT3
/// @notice Interface for the deployed PoseidonT3 contract
interface IPoseidonT3 {
    function poseidon(uint256[2] memory input) external pure returns (uint256);
}

/// @title IPoseidonT4
/// @notice Interface for the deployed PoseidonT4 contract
interface IPoseidonT4 {
    function poseidon(uint256[3] memory input) external pure returns (uint256);
}

/// @title PoseidonT3
/// @notice Poseidon hash function for 2 inputs (T=3 means 2 inputs + 1 capacity)
/// @dev Calls an external deployed Poseidon contract generated by circomlibjs
library PoseidonT3 {
    // Address of deployed PoseidonT3 contract on Mantle Sepolia
    address constant POSEIDON_T3 = 0xc08E75955D081bE4Bc43a67f7F029115767B7155;

    function hash(uint256[2] memory input) internal view returns (uint256) {
        return IPoseidonT3(POSEIDON_T3).poseidon(input);
    }
}

/// @title PoseidonT4
/// @notice Poseidon hash function for 3 inputs (T=4 means 3 inputs + 1 capacity)
library PoseidonT4 {
    // Address of deployed PoseidonT4 contract - must be set before deployment
    address constant POSEIDON_T4 = 0x0000000000000000000000000000000000000002;

    function hash(uint256[3] memory input) internal view returns (uint256) {
        return IPoseidonT4(POSEIDON_T4).poseidon(input);
    }
}
