// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Script, console2} from "forge-std/Script.sol";

/**
 * @title DeployPoseidon
 * @notice Deploys Poseidon hasher contracts from pre-generated bytecode
 * @dev Run with: forge script script/DeployPoseidon.s.sol --rpc-url mantle_sepolia --broadcast
 */
contract DeployPoseidon is Script {
    function run() public {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");

        // Read bytecode from file
        string memory json = vm.readFile("poseidon-bytecode.json");
        bytes memory poseidonT3Bytecode = vm.parseJsonBytes(json, ".poseidonT3.bytecode");

        vm.startBroadcast(deployerPrivateKey);

        // Deploy PoseidonT3 (2 inputs)
        address poseidonT3;
        assembly {
            poseidonT3 := create(0, add(poseidonT3Bytecode, 0x20), mload(poseidonT3Bytecode))
        }
        require(poseidonT3 != address(0), "PoseidonT3 deployment failed");
        console2.log("PoseidonT3 deployed at:", poseidonT3);

        vm.stopBroadcast();

        // Output instructions for next step
        console2.log("\n=== Next Steps ===");
        console2.log("1. Update packages/contracts/src/libraries/Poseidon.sol");
        console2.log("   Set POSEIDON_T3 =", poseidonT3);
        console2.log("2. Run: forge script script/DeployShieldedPool.s.sol --rpc-url mantle_sepolia --broadcast");
    }
}
